# ansible is going to collect the information of the remote node and all its facts and stores it as an variables is called as facts

- name: Facts
  hosts: localhost
  tasks:
  - name: Print fact
    ansible.builtin.debug:
      msg: "{{ ansible_hostname }}"

# o/p:- msg: "ip-172-31-82-141" (above playbook gives ip address as output (here the local host is already declared as the part of gathering facts and we are using that))
# all facts and variables can be refered here :-  https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html