- name: Demo on Variables
  hosts: all
  vars:
    URL: google.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: "URL = {{ URL }}" #same like shell you care accessing variables with prefix $, here variable will be under {{ }}